# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answertext', models.CharField(max_length=100)),
                ('answerNumber', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, upload_to=b'/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('num_answers', models.IntegerField(default=0)),
                ('questionNumber', models.IntegerField(default=0)),
                ('image', models.ImageField(default=None, upload_to=b'/images/')),
                ('answers', models.ManyToManyField(blank=True, to='quizzes.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quiz_Title', models.CharField(max_length=100)),
                ('Quiz_Description', models.CharField(max_length=1000)),
                ('image', models.ImageField(default=None, upload_to=b'/images/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('timesTaken', models.IntegerField(default=0)),
                ('Quiz_Type', models.CharField(max_length=1000)),
                ('questions', models.ManyToManyField(blank=True, to='quizzes.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quiz_Scoring', models.CharField(max_length=100)),
                ('Quiz_Result', models.CharField(max_length=100)),
                ('resultNumber', models.IntegerField()),
                ('Quiz_Result_Explanation', models.CharField(max_length=1000)),
                ('image', models.ImageField(default=None, upload_to=b'/images/')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='results',
            field=models.ManyToManyField(blank=True, to='quizzes.Result'),
        ),
    ]
