# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20161005_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='answer',
            name='correctAnswer',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
