# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20161006_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answertext',
            new_name='answerText',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='results',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
